In [1]:
import numpy as np

In [25]:
first_vector = np.array([1,2,3])
second_vector = np.array([5,6,7])

In [72]:
first_matrix = np.array([[1,2,3],[5,6,7],[9,0,8]])
second_matrix = np.array([[1,2,3],[5,6,7],[9,0,8]])

# Addition for vector

In [73]:
first_vector+second_vector

array([ 4,  9, 17])

# addition for matrix

In [74]:
first_matrix+second_matrix

array([[ 2,  4,  6],
       [10, 12, 14],
       [18,  0, 16]])

# Subtraction for vector

In [75]:
first_vector-second_vector

array([ -4,  -7, -13])

# Subtraction for matrix

In [76]:
first_matrix-second_matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Multiplication for vector

In [77]:
first_vector*second_vector

array([ 0,  8, 30])

# Multiplication for martix

In [78]:
first_matrix*second_matrix

array([[ 1,  4,  9],
       [25, 36, 49],
       [81,  0, 64]])

# Scalar multiplication in vector

In [79]:
2*first_vector

array([0, 2, 4])

# Scalar multiplication in matrix

In [80]:
2*first_matrix

array([[ 2,  4,  6],
       [10, 12, 14],
       [18,  0, 16]])

# Dot product

[1,2,4].[2,-1,9] = 1(2)+2(-1)+4(9) = 2-2+36 = 36

# Facts : |[1,2,4].[2,-1,9]| = |[1,2,4]| .|[2,-1,9]| .|cos(0.5603)|
        is the vectors are orthogonal, the dot product is 0

In [81]:
np.dot(first_vector,second_vector)

38

# Checking vectors are orthogonal in dot product

In [82]:
def are_orthogonal(vect1,vect2):
    return np.dot(vect1,vect2) == 0

In [83]:
are_orthogonal(first_vector,second_vector)

False

# cross product and length

See in note how to do claculation

[1,2,4]*[2,-1,9] = [22,-1,-5]

Facts : |[1,2,4]*[2,-1,9]| =|[1,2,4]|*|[2,-1,9]| *|sin(0.5603)|

if the vectors are parallel the cross product is [0,0,0]

The cross product is always orthogonal on both vectors

In [84]:
np.cross(first_vector,second_vector)

array([-1,  8, -4])

In [85]:
# cross product for two dimentional vector:
np.cross(np.arange(2),np.arange(1,3))

array(-1)

example

In [86]:
cross = np.cross(first_vector,second_vector)

In [87]:
np.dot(first_vector,cross)

0

In [88]:
np.dot(second_vector,cross)

0

# to do more complex linear algebra we need linear algera library

In [89]:
from numpy import linalg

# length of the vector

In [90]:
linalg.norm(first_vector)

2.23606797749979

In [91]:
linalg.norm(second_vector)

17.46424919657298

In [92]:
linalg.norm(first_matrix)

16.401219466856727

In [93]:
linalg.norm(second_matrix)

16.401219466856727

exampe

In [94]:
def angle(vect1,vect2):
    cos_angle = np.dot(vect1,vect2)/(linalg.norm(vect1)*linalg.norm(vect2))
    return np.arccos(cos_angle) # take inverse of vector
angle(first_vector,second_vector)

0.232556941804909

# Exercise

In [95]:
# Importing the numpy package with the alias np
import numpy as np

# Defining the matrix called my_matrix
first_vector = np.arange(3)
second_vector = np.array([4, 8, 15])

# YOURE CODE GOES BELOW HERE!

# Find the dot product of the vectors above
dot_product = np.dot(first_vector,second_vector)
print("dot product is",dot_product)
# Find the cross product of the vectors above
cross_product = np.cross(first_vector,second_vector)
print("cross product is",cross_product)

dot product is 38
cross product is [-1  8 -4]


# Matrix operation

# point wise matrix multiplication see in note

In [96]:
first_matrix*second_matrix

array([[ 1,  4,  9],
       [25, 36, 49],
       [81,  0, 64]])

# matrix product see in note

In [97]:
first_matrix@first_vector

array([ 8, 20, 16])

In [98]:
first_matrix@second_matrix

array([[ 38,  14,  41],
       [ 98,  46, 113],
       [ 81,  18,  91]])

In [100]:
# other notation for doing matrix product
np.matmul(first_matrix,second_matrix)

array([[ 38,  14,  41],
       [ 98,  46, 113],
       [ 81,  18,  91]])

In [101]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
np.eye(3)@first_matrix

array([[1., 2., 3.],
       [5., 6., 7.],
       [9., 0., 8.]])

In [103]:
np.eye(3)@first_vector

array([0., 1., 2.])

# matrix power

In [104]:
first_matrix@first_matrix@first_matrix

array([[ 477,  160,  540],
       [1345,  472, 1520],
       [ 990,  270, 1097]])

# Using linear algebra calulate matrix power

In [106]:
linalg.matrix_power(first_matrix,3)

array([[ 477,  160,  540],
       [1345,  472, 1520],
       [ 990,  270, 1097]])

# Transpose

In [107]:
first_matrix

array([[1, 2, 3],
       [5, 6, 7],
       [9, 0, 8]])

In [109]:
# for transpose .T
first_matrix.T

array([[1, 5, 9],
       [2, 6, 0],
       [3, 7, 8]])

In [110]:
first_matrix.transpose()

array([[1, 5, 9],
       [2, 6, 0],
       [3, 7, 8]])

# Exercise

In [118]:
# Importing the numpy package with the alias np
import numpy as np

# Defining the matrix called my_matrix
my_matrix = np.array([[1, 4, 5], [10, 13, 9], [10, 8, 5]])
print("my matrix is\n",my_matrix)
# YOURE CODE GOES BELOW HERE!


# The multiplication of the matrix with its transpose
my_matrix_mul_transpose = my_matrix.transpose()
print("transpose is\n",my_matrix_mul_transpose)
matrix_mul= my_matrix*my_matrix_mul_transpose
print("matrix multilpication is\n",matrix)

my matrix is
 [[ 1  4  5]
 [10 13  9]
 [10  8  5]]
transpose is
 [[ 1 10 10]
 [ 4 13  8]
 [ 5  9  5]]
matrix multilpication is
 [[  1  40  50]
 [ 40 169  72]
 [ 50  72  25]]


# Solve linear system I in numpy

How to do diterminent in numpy:
    Is the matrix is invertable or not,
        if the matrix is 0 is not invertable,
        if the matrix is not 0 it is invertable,

In [120]:
#to take determinent
linalg.det(first_matrix)

-68.00000000000001

In [121]:
linalg.det(second_matrix)

-68.00000000000001

In [125]:
non_invertable = np.array([[1,2,0],[-2,10,3],[-3,8,3]])

In [129]:
linalg.det(non_invertable) # this is approximate value

3.108624468950436e-15

In [130]:
# to get round value
np.around(linalg.det(non_invertable),10)

0.0

# Inverse matrices

In [132]:
linalg.inv(first_matrix)@first_matrix # it is approxiamte value

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.94289029e-16,  1.00000000e+00,  0.00000000e+00],
       [ 9.71445147e-17,  0.00000000e+00,  1.00000000e+00]])

In [134]:
#to get exact value
np.around(linalg.inv(first_matrix)@first_matrix,10)

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [142]:
linalg.inv(non_invertable) # it is approximate value

array([[ 1.93011413e+15, -1.93011413e+15,  1.93011413e+15],
       [-9.65057063e+14,  9.65057063e+14, -9.65057063e+14],
       [ 4.50359963e+15, -4.50359963e+15,  4.50359963e+15]])

# Linear system II in numpy

# Ax = B is matrix 'A' with some unknown x = some vector B

cases:
  1. have unique values
  2. have non-solution
  3. have infinity many solution

Problem with have unique solution

In [143]:
linalg.solve(first_matrix,first_vector)

array([ 0.35294118,  0.04411765, -0.14705882])

In [144]:
first_matrix @ linalg.solve(first_matrix,first_vector)

array([-2.77555756e-17,  1.00000000e+00,  2.00000000e+00])

problem with non solution

In [147]:
linalg.solve(non_invertable,first_vector)

array([ 1.93011413e+15, -9.65057063e+14,  4.50359963e+15])

In [148]:
non_invertable@linalg.solve(non_invertable,first_vector)

array([-0.5,  1. ,  1. ])

problem with infenitely many solution

In [149]:
third_vector = np.array([1,3,4])

In [150]:
linalg.solve(non_invertable,third_vector)

array([ 3.86022825e+15, -1.93011413e+15,  9.00719925e+15])

In [151]:
non_invertable@linalg.solve(non_invertable,third_vector)

array([0., 2., 2.])