# Basic Linear Algebra

#    "This exercise set is all about doing standard linear algebra exercises using NumPy. "

In [1]:
#DON'T MODIFY THIS CELL, ONLY RUN IT.
# Importing NumPy as np
import numpy as np

# Exercise 1: Import the Linalg Submodule

In [3]:
# Importing the linalg submodule from NumPy
from numpy import linalg

# Exercise 2: Simple Vector Operations
    Exercise 2a: 
        Are any of the vectors $[1, 2, 3]$  and $[2, 3, 4]$  parallel? What about orthogonal?

In [4]:
# Make the vectors
v1=np.array([1,2,3])
v2=np.array([2,3,4])

In [5]:
# Checking if parallel
print("The cross product between is", np.cross(v1, v2))

The cross product between is [-1  2 -1]


In [7]:
# check if orthogonal
print("The inner product is", np.dot(v1, v2))

The inner product is 20


Exercise 2b:
    Can you find the angle between the vector $[1, 2, 3]$ and $[2, 3, 4]$
   

In [9]:
# Defining the angle function
def angle(vect1,vect2):
    cos_angle = np.dot(vect1,vect2)/(linalg.norm(vect1)*linalg.norm(vect2))
    return np.arccos(cos_angle) # take inverse of vector
# Finding the angle
print("the angle is",angle(v1,v2))

the angle is 0.12186756768575456


# Exercise 3: Simple Matrix Operations

In [12]:
A=np.array([[1,1,2],[1,1,1],[1,1,1]])
B=np.array([[1,0,0],[0,1,-2],[0,0,1]])

Exercise 3a: 
    Find the matrix product

In [14]:
print("the matrix product is\n",A@B)

the matrix product is
 [[ 1  1  0]
 [ 1  1 -1]
 [ 1  1 -1]]


Exercise 3b:
    Find the matrix product $B^{-1}A^5$."

In [25]:
linalg.inv(B) @ linalg.matrix_power(A, 5)

array([[142., 142., 185.],
       [327., 327., 426.],
       [109., 109., 142.]])

Exercise 3c: 
    "Find the transpose of $A$, namely $A^T$. Compute the product $A A^T$.
   

In [27]:
print("the transpose of A is\n",A.T)

the transpose of A is
 [[1 1 1]
 [1 1 1]
 [2 1 1]]


In [29]:
print("the product of A and A trsnspose\n",A@A.T)

the product of A and A trsnspose
 [[6 4 4]
 [4 3 3]
 [4 3 3]]


# Exercise 4: Balancing Chemical Equations

"In this exercise we are going to use NumPy to balance a set of chemical equations. The question is how to balance the equation\n",
    "$$x*C_4H_{10}+y*O_2 = v*H_2O + w*CO_2.$$\n",
    "Written as vectors this becomes\n",
    "$$x*[4,10,0]+y*[0,0,2]=z*[0,2,1] + w*[1,0,2],$$\n",
    "or equivalently,\n",
    

 Exercise 4a: 
    "Find out if the matrix is invertible.

In [54]:
chem_mat = np.array([[4, 0, 0], [10, 0, -2], [0, 2, -1]])

In [55]:
linalg.det(chem_mat) # # Since it is nonzero, the matrix is invertible.

16.000000000000007

Exercise 4b: 
    "Solve the linear system with $w=1$.

In [56]:
solution = linalg.solve(chem_mat, np.array([1, 0, 2]))
print("The solution is: ", solution)

The solution is:  [0.25  1.625 1.25 ]


Exercise 4c:
    "Having 0.25 of a carbon atom doesn’t really make sense. Multiply the vector with the whole numbers from 1 to 10 to see when the solution consists of only whole numbers."
   

In [78]:
for i in range(1, 11):
        print("The solution multiplied with", i*solution)

The solution multiplied with [0.25  1.625 1.25 ]
The solution multiplied with [0.5  3.25 2.5 ]
The solution multiplied with [0.75  4.875 3.75 ]
The solution multiplied with [1.  6.5 5. ]
The solution multiplied with [1.25  8.125 6.25 ]
The solution multiplied with [1.5  9.75 7.5 ]
The solution multiplied with [ 1.75  11.375  8.75 ]
The solution multiplied with [ 2. 13. 10.]
The solution multiplied with [ 2.25  14.625 11.25 ]
The solution multiplied with [ 2.5  16.25 12.5 ]


Exercise 4d: \n",
    "Write up the balanced equation, in other words, what is $x,$ $y,$ $z,$ and $w$?"
    

In [57]:
# 2*C_4H_{10}+13*O_2 = 10*H_2O + 8*CO_2